"""create characters and guilds tables

Revision ID: c1107f963a49
Revises: 68ae5dc6e30a
Create Date: 2026-03-05 00:02:32.748971

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c1107f963a49"
down_revision: str | Sequence[str] | None = "68ae5dc6e30a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guilds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("realm", sa.String(length=100), nullable=False),
        sa.Column("faction", sa.String(length=10), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=True),
        sa.Column("progression_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "last_synced",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "realm", name="uq_guild_name_realm"),
    )
    op.create_table(
        "characters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("realm", sa.String(length=100), nullable=False),
        sa.Column("class", sa.String(length=30), nullable=False),
        sa.Column("race", sa.String(length=30), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("faction", sa.String(length=10), nullable=False),
        sa.Column("guild_name", sa.String(length=100), nullable=True),
        sa.Column(
            "last_synced",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "realm", name="uq_character_name_realm"),
    )
    op.create_table(
        "character_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.Column("gear_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("talents_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stats_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("arena_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reputation_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "snapshot_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["character_id"],
            ["characters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_snapshot_character_time",
        "character_snapshots",
        ["character_id", "snapshot_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_snapshot_character_time", table_name="character_snapshots")
    op.drop_table("character_snapshots")
    op.drop_table("characters")
    op.drop_table("guilds")
    # ### end Alembic commands ###
